version: '3.8'

x-testing-host: &testing-host-base
  image: coolify-testing-host
  build:
    dockerfile: Dockerfile
    context: ./docker/testing-host
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - ./docker/testing-host/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
  networks:
    - coolify

services:
  php:
    image: "coolify:${TAG:-4}"
    build:
      context: ./docker/dev
      dockerfile: Dockerfile
      args:
        WWWGROUP: '${WWWGROUP}'
    ports:
      - "${APP_PORT:-8000}:80"
      - "${VITE_PORT:-5173}:${VITE_PORT:-5173}"
    environment:
      WWWUSER: "${WWWUSER}"
      LARAVEL_SAIL: 1
      XDEBUG_MODE: "${SAIL_XDEBUG_MODE:-off}"
      XDEBUG_CONFIG: "${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}"
    volumes:
      - .:/var/www/html
    networks:
      - coolify
    depends_on:
      postgres:
        condition: service_healthy
  postgres:
    image: postgres:15-alpine
    ports:
      - "${FORWARD_DB_PORT:-5432}:5432"
    volumes:
      - db-coolify:/var/lib/postgresql/data
    networks:
      - coolify
    environment:
      POSTGRES_USER: "${DB_USERNAME}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_DB: "${DB_DATABASE}"
      POSTGRES_HOST_AUTH_METHOD: "trust"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U coolify",
          "-d",
          "coolify"
        ]
      retries: 5
      timeout: 10s
  testing-host:
    <<: *testing-host-base
    container_name: coolify-testing-host
  testing-host2:
    <<: *testing-host-base
    container_name: coolify-testing-host-2

volumes:
  db-coolify:
    driver: local

networks:
  coolify:
    driver: bridge



