version: '3.8'

services:
 coolify:
    build:
      context: .
      dockerfile: Dockerfile-dev
    command: bash -c 'pnpm install && pnpm db:push && pnpm db:seed && pnpm dev'
    environment:
      - COOLIFY_CONTAINER_DEV=true
      - COOLIFY_APP_ID=random-local-id
      - COOLIFY_SECRET_KEY=12341234123412341234123412341234
      - COOLIFY_DATABASE_URL=file:../db/dev.db
      - GITPOD_WORKSPACE_URL=${GITPOD_WORKSPACE_URL}
      - CODESANDBOX_HOST=${CODESANDBOX_HOST}
    container_name: coolify
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
        mode: host
      - target: 3001
        published: 3001
        protocol: tcp
        mode: host
      - target: 5555
        published: 5555
        protocol: tcp
        mode: host
    volumes:
      - ./:/app
      - '/var/run/docker.sock:/var/run/docker.sock'
      - /tmp:/tmp
    networks:
      - coolify-infra
 fluent-bit:
    image: coollabsio/coolify-fluent-bit:1.0.0
    command: /fluent-bit/bin/fluent-bit -c /fluent-bit/etc/fluent-bit-dev.conf
    container_name: coolify-fluentbit
    volumes:
      - ./logs:/logs
    ports:
      - target: 24224
        published: 24224
        protocol: tcp
        mode: host
    networks:
      - coolify-infra
networks:
  coolify-infra:
    attachable: true
    name: coolify-infra
