version: '3.8'

services:
  haproxy: 
    image: coollabsio/coolify-haproxy-alpine:latest
    container_name: coolify-haproxy
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    networks:
      - coolify
    volumes:
      - './data/haproxy/:/usr/local/etc/haproxy/'
    ports: 
      - "80:80"
      - "443:443"
      - "8404:8404"
      - "5555:5555"
      - "3306:3306"

networks:
  coolify:
    attachable: true
    name: coolify
