blank_issues_enabled: false
contact_links:
  - name: ğŸ¤” Community Support (Chat)
    url: https://coollabs.io/discord
    about: Reach out to us on Discord.
  - name: ğŸ™‹â€â™‚ï¸ Feature Requests
    url: https://github.com/coollabsio/coolify/discussions/categories/new-features
    about: All feature requests will be discussed here.
