services:
    coolify:
        container_name: coolify
        restart: always
        working_dir: /var/www/html
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        networks:
            - coolify
        depends_on:
            - postgres
            - redis
            - soketi
    postgres:
        image: postgres:15-alpine
        container_name: coolify-db
        restart: always
        networks:
            - coolify
    redis:
        image: redis:alpine
        container_name: coolify-redis
        restart: always
        networks:
            - coolify
    soketi:
        image: 'quay.io/soketi/soketi:1.6-16-alpine'
        container_name: coolify-realtime
        restart: always
        networks:
            - coolify
networks:
    coolify:
        name: coolify
        driver: bridge
        external: false
